os:
 - linux
language: node_js
node_js: 8

install:
  - 'npm install'

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
